FROM buildpack-deps:stretch as builder

WORKDIR /build

RUN { set -ex; \
	apt-get update; \
	apt-get install --no-install-recommends -y nodejs; \
}

ARG TAG=cjdns-v20.1
RUN git clone https://github.com/cjdelisle/cjdns.git cjdns --depth 1 --branch $TAG

RUN { set -ex; \
	cd cjdns; \
	./do; \
}

FROM debian:stretch-slim
COPY start-cjdns /usr/bin/
VOLUME /data/cjdns
CMD ["start-cjdns"]
COPY --from=builder /build/cjdns/cjdroute /usr/bin/
